---
title: "Activity 3"
output: github_document 
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidymodels)
library(GGally)
```

## Day 1

```{r Task3 Data Loading}

hfi <- readr::read_csv("https://www.openintro.org/data/csv/hfi.csv")
hfi
```

```{r Task3 Data Filtering}
hfi_2016 <- hfi %>% filter(year==2016)

```

```{r}
hfi_2016 %>% 
  select(ends_with("_score")) %>% 
  ggpairs()
```

```{r}
m_hr_ef <- lm(pf_score ~ hf_score + ef_score, data = hfi_2016)
tidy(m_hr_ef)
```


```{r}
library(modelr)
library(broom)
library(plotly)

# 1. Generate an evenly spaced grid of points from the data
grid <- hfi_2016 %>%
  data_grid(
    hf_score = seq_range(hf_score, n = 50),
    ef_score = seq_range(ef_score, n = 50)
  )

# 2. Feed generated grid values into model
tidy_planes <- m_hr_ef %>%
  augment(newdata = grid)

# 3. Build the plane
x <- unique(grid$hf_score)
y <- unique(grid$ef_score)

plane <- tidy_planes %>%
  pull(.fitted) %>%
  matrix(nrow = length(x), byrow = TRUE)

# 4. Visualize regression plane together with the data points
plot_ly(data = hfi_2016, z = ~pf_score, x = ~hf_score, y = ~ef_score, opacity = 0.6) %>%
  #add_markers(text = ~case, marker = list(size = 2)) %>%
  add_surface(
    x = ~x, y = ~y, z = ~plane, 
    showscale = FALSE, 
    surfacecolor = matrix(0.5, nrow = nrow(plane), ncol = ncol(plane)), 
    cauto = FALSE,
    cmax = 1
  )
```

```{r}
library(scatterplot3d)
hfi_scatter_3d <- hfi_2016 %>% select(hf_score, ef_score, pf_score)
scatterplot3d(hfi_scatter_3d[,1:3],
              pch = 15,
              color="steelblue",
              grid = TRUE)
```

## Day 2

```{r}
# review any visual patterns
hfi %>% 
  select(pf_score, pf_expression_influence, pf_expression_control) %>% 
  ggpairs()

#fit the mlr model
m_pf <- lm(pf_score ~ pf_expression_influence + pf_expression_control, data = hfi)
tidy(m_pf)
```

```{r}
summary(m_pf)
```

```{r}
glance(m_pf)
```

```{r}
# obtain fitted values and residuals
m_pf_aug <- augment(m_pf)

# plot fitted values and residuals
ggplot(data = m_pf_aug, aes(x = .fitted, y = .resid)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  xlab("Fitted values") +
  ylab("Residuals")
```

```{r}
ggplot(data = m_pf_aug, aes(x = .resid)) +
  geom_histogram(binwidth = 0.25) +
  xlab("Residuals")
```

```{r}
hfi %>% 
  filter(countries == "United States" & year == 2016) %>% 
  select(pf_score, pf_expression_influence, pf_expression_control)
```

```{r}
hfi %>% 
  filter(countries == "United States" & year == 2016) %>% 
  predict(m_pf, .)
```






